spring.application.name=Libranos

server.port=${PORT:8005}

spring.datasource.url=jdbc:postgresql://dpg-d92p3qflk1mc73c78m1g-a:5432/banco_libranos
spring.datasource.username=banco_libranos_user
spring.datasource.password=VDAkSMClT4tIUH4XkUs2TZxx2cJxMQ5Z
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000